### ISSUE TITLE
after a first installation on magento 2.4.3-p3

### ISSUE THREAD

**Issue by hielh** [Alekseon/magento2-custom-forms-builder#15]
I get this error:
![image](https://github.com/Alekseon/magento2-custom-forms-builder/assets/909932/6ee6a767-f03d-4a64-8489-ab9ffa16e2f0)

alekseon_custom_form table doens't existe, any idea please

**Comment by hielh** [comment]
it works after I delete all modules and tables et reinstall the package.

**Comment by marcinfr** [comment]
Hi, 
Did error occur during updating module? or was it fresh installation?

**Comment by shiyam312001** [comment]
All of Works Well, But Images Only Not Uploaded In Database .

**Comment by marcinfr** [comment]
Hi @shiyam312001 
Thank You for Your feedback
I have found issue with images upload and its already fixed in package alekseon/alekseon-eav version 101.2.5
What alekseon-eav version do You have? If its below 101.2.5, please update it.
If issue still persists, please give us more information about it.
Also I suggest to open a new issue about images upload if its not related to this one.

**Comment by marcinfr** [comment]
@hielh @shiyam312001 
This issue has been closed since there has not been any recent activity. Please open a new issue for related bugs.
