### ISSUE TITLE
Multilangual checkbox label not working

### ISSUE THREAD

**Issue by mtkumar82** [Alekseon/magento2-custom-forms-builder#9]
Hi,
I installed this extension and working fine. But multiple checkbox not working for multilangual. Field heading is translating fine, but checkbox label not translating. Please check the issue here.
https://zayron.it/become-a-supplier
You can try to change the language from top.  Also I added translation in form setting in magento admin atrea. Pleaase suggest how I can show multiple checkboxes field label in multilangual?

Thanks

**Comment by marcinfr** [comment]
Hello,

It has been fixed in package alekseon/alekseon-eav in version: 101.0.12

You can update this package by composer:
`composer update alekseon/alekseon-eav:101.0.12`

or you can update "widget forms" module by composer to latest version by:
`composer update alekseon/widget-forms alekseon/alekseon-eav alekseon/custom-forms-builder`
